import './SummaryCard.css'

function SummaryCard({ summary, modelInfo, onGenerateSummary, isGenerating, alertsCount }) {
    const formatDate = (timestamp) => {
        return new Date(timestamp).toLocaleString([], {
            month: 'short',
            day: 'numeric',
            hour: '2-digit',
            minute: '2-digit'
        })
    }

    // Parse summary text into sections
    const parseSummary = (text) => {
        if (!text) return { title: '', aiAnalysis: '', alerts: [] }

        const lines = text.split('\n').filter(l => l.trim())
        let title = ''
        let aiAnalysis = ''
        let criticalAlerts = []
        let warningAlerts = []
        let currentSection = ''

        for (const line of lines) {
            if (line.includes('**Clinical Summary for')) {
                title = line.replace(/\*\*/g, '')
            } else if (line.includes('**AI Analysis')) {
                currentSection = 'ai'
            } else if (line.includes('🔴 CRITICAL')) {
                currentSection = 'critical'
            } else if (line.includes('🟡 WARNING')) {
                currentSection = 'warning'
            } else if (line.includes('**Active Alerts')) {
                // Skip header
            } else if (currentSection === 'ai' && !line.includes('**')) {
                aiAnalysis = line.trim()
            } else if (currentSection === 'critical' && line.trim().startsWith('•')) {
                criticalAlerts.push(line.replace('•', '').trim())
            } else if (currentSection === 'warning' && line.trim().startsWith('•')) {
                warningAlerts.push(line.replace('•', '').trim())
            }
        }

        return { title, aiAnalysis, criticalAlerts, warningAlerts }
    }

    const parsed = summary?.text ? parseSummary(summary.text) : null

    return (
        <div className="summary-card glass-card">
            <div className="summary-header">
                <h3 className="summary-title">
                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                        <path d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
                    </svg>
                    AI Clinical Summary
                </h3>
                <div className="ai-badge">
                    <span className="ai-icon">✨</span>
                    Generated by AI
                </div>
            </div>

            <div className="summary-content">
                {summary && parsed ? (
                    <div className="summary-sections">
                        {parsed.title && (
                            <div className="summary-patient-title">{parsed.title}</div>
                        )}

                        {parsed.aiAnalysis && (
                            <div className="summary-section ai-section">
                                <div className="section-header">
                                    <span className="section-icon">🤖</span>
                                    <span className="section-title">AI Analysis (Flan-T5)</span>
                                </div>
                                <p className="section-content">{parsed.aiAnalysis}</p>
                            </div>
                        )}

                        {(parsed.criticalAlerts?.length > 0 || parsed.warningAlerts?.length > 0) && (
                            <div className="summary-section alerts-section">
                                <div className="section-header">
                                    <span className="section-icon">⚠️</span>
                                    <span className="section-title">Active Alerts</span>
                                </div>

                                {parsed.criticalAlerts?.length > 0 && (
                                    <div className="alert-group critical">
                                        <div className="alert-group-header">🔴 Critical</div>
                                        <ul className="alert-list">
                                            {parsed.criticalAlerts.map((alert, i) => (
                                                <li key={i} className="alert-item critical">{alert}</li>
                                            ))}
                                        </ul>
                                    </div>
                                )}

                                {parsed.warningAlerts?.length > 0 && (
                                    <div className="alert-group warning">
                                        <div className="alert-group-header">🟡 Warning</div>
                                        <ul className="alert-list">
                                            {parsed.warningAlerts.map((alert, i) => (
                                                <li key={i} className="alert-item warning">{alert}</li>
                                            ))}
                                        </ul>
                                    </div>
                                )}
                            </div>
                        )}

                        {summary.error && (
                            <p className="summary-text error">{summary.text}</p>
                        )}
                    </div>
                ) : (
                    <div className="no-summary">
                        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                            <circle cx="12" cy="12" r="10" />
                            <path d="M8 12h.01M12 12h.01M16 12h.01" />
                        </svg>
                        <p>Click the button below to generate a summary of the last {Math.min(alertsCount || 0, 5)} alerts.</p>
                    </div>
                )}
            </div>

            <div className="summary-actions">
                <button
                    className="generate-summary-btn"
                    onClick={onGenerateSummary}
                    disabled={isGenerating || alertsCount === 0}
                >
                    {isGenerating ? (
                        <>
                            <span className="btn-spinner"></span>
                            Generating...
                        </>
                    ) : (
                        <>
                            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                                <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z" />
                            </svg>
                            Generate Summary ({Math.min(alertsCount || 0, 5)} alerts)
                        </>
                    )}
                </button>
            </div>

            {summary && !summary.error && (
                <div className="summary-footer">
                    <span className="summary-time">
                        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                            <circle cx="12" cy="12" r="10" />
                            <path d="M12 6v6l4 2" />
                        </svg>
                        {formatDate(summary.timestamp)}
                    </span>
                    {modelInfo && (
                        <div className="model-info">
                            <span className="model-name">{modelInfo.name}</span>
                            <span className="model-version">v{modelInfo.version}</span>
                        </div>
                    )}
                </div>
            )}
        </div>
    )
}

export default SummaryCard
