import './SummaryCard.css'

function SummaryCard({ summary, modelInfo }) {
    const formatDate = (timestamp) => {
        return new Date(timestamp).toLocaleString([], {
            month: 'short',
            day: 'numeric',
            hour: '2-digit',
            minute: '2-digit'
        })
    }

    return (
        <div className="summary-card glass-card">
            <div className="summary-header">
                <h3 className="summary-title">
                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                        <path d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
                    </svg>
                    AI Clinical Summary
                </h3>
                <div className="ai-badge">
                    <span className="ai-icon">✨</span>
                    Generated by AI
                </div>
            </div>

            <div className="summary-content">
                {summary ? (
                    <p className="summary-text">{summary.text}</p>
                ) : (
                    <div className="no-summary">
                        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                            <circle cx="12" cy="12" r="10" />
                            <path d="M8 12h.01M12 12h.01M16 12h.01" />
                        </svg>
                        <p>Generating clinical summary...</p>
                    </div>
                )}
            </div>

            {summary && (
                <div className="summary-footer">
                    <span className="summary-time">
                        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                            <circle cx="12" cy="12" r="10" />
                            <path d="M12 6v6l4 2" />
                        </svg>
                        {formatDate(summary.timestamp)}
                    </span>
                    {modelInfo && (
                        <div className="model-info">
                            <span className="model-name">{modelInfo.name}</span>
                            <span className="model-version">v{modelInfo.version}</span>
                        </div>
                    )}
                </div>
            )}
        </div>
    )
}

export default SummaryCard
